"""
This file is auto generated by the code generation script.
Do not modify this file manually.
Use the `make codegen` command to regenerate.

当前文件为自动生成的控制 API 客户端代码。请勿手动修改此文件。
使用 `make codegen` 命令重新生成。

source: agentrun/tool/__tool_async_template.py

Tool 资源类 / Tool Resource Class

提供工具资源的面向对象封装和完整生命周期管理。
Provides object-oriented wrapper and complete lifecycle management for tool resources.
"""

from typing import Any, Dict, List, Optional

import pydash

from agentrun.utils.config import Config
from agentrun.utils.log import logger
from agentrun.utils.model import BaseModel

from .model import (
    McpConfig,
    ToolCodeConfiguration,
    ToolContainerConfiguration,
    ToolInfo,
    ToolLogConfiguration,
    ToolNetworkConfiguration,
    ToolOSSMountConfig,
    ToolSchema,
    ToolType,
)


class Tool(BaseModel):
    """工具资源 / Tool Resource

    提供工具的查询、调用等功能。
    Provides query, invocation and other functionality for tools.

    Attributes:
        code_configuration: 代码包配置 / Code configuration
        container_configuration: 容器配置 / Container configuration
        created_time: 创建时间 / Creation time
        data_endpoint: 数据链路端点 / Data endpoint
        description: 描述 / Description
        environment_variables: 环境变量 / Environment variables
        gpu: GPU 配置 / GPU configuration
        internet_access: 是否允许公网访问 / Whether internet access is allowed
        last_modified_time: 最后修改时间 / Last modified time
        log_configuration: 日志配置 / Log configuration
        mcp_config: MCP 配置 / MCP configuration
        memory: 内存大小(MB) / Memory size in MB
        name: 工具名称 / Tool name
        network_config: 网络配置 / Network configuration
        oss_mount_config: OSS 挂载配置 / OSS mount configuration
        protocol_spec: 协议规格(OpenAPI JSON) / Protocol spec (OpenAPI JSON)
        protocol_type: 协议类型 / Protocol type
        status: 状态 / Status
        timeout: 超时时间(秒) / Timeout in seconds
        tool_id: 工具 ID / Tool ID
        tool_name: 工具名称 / Tool name
        tool_type: 工具类型(MCP/FUNCTIONCALL) / Tool type
        version_id: 版本 ID / Version ID
    """

    code_configuration: Optional[ToolCodeConfiguration] = None
    """代码包配置 / Code configuration"""

    container_configuration: Optional[ToolContainerConfiguration] = None
    """容器配置 / Container configuration"""

    created_time: Optional[str] = None
    """创建时间 / Creation time"""

    data_endpoint: Optional[str] = None
    """数据链路端点 / Data endpoint"""

    description: Optional[str] = None
    """描述 / Description"""

    environment_variables: Optional[Dict[str, str]] = None
    """环境变量 / Environment variables"""

    gpu: Optional[str] = None
    """GPU 配置 / GPU configuration"""

    internet_access: Optional[bool] = None
    """是否允许公网访问 / Whether internet access is allowed"""

    last_modified_time: Optional[str] = None
    """最后修改时间 / Last modified time"""

    log_configuration: Optional[ToolLogConfiguration] = None
    """日志配置 / Log configuration"""

    mcp_config: Optional[McpConfig] = None
    """MCP 配置 / MCP configuration"""

    memory: Optional[int] = None
    """内存大小(MB) / Memory size in MB"""

    name: Optional[str] = None
    """工具名称 / Tool name"""

    network_config: Optional[ToolNetworkConfiguration] = None
    """网络配置 / Network configuration"""

    oss_mount_config: Optional[ToolOSSMountConfig] = None
    """OSS 挂载配置 / OSS mount configuration"""

    protocol_spec: Optional[str] = None
    """协议规格(OpenAPI JSON 字符串) / Protocol spec (OpenAPI JSON string)"""

    protocol_type: Optional[str] = None
    """协议类型 / Protocol type"""

    status: Optional[str] = None
    """状态 / Status"""

    timeout: Optional[int] = None
    """超时时间(秒) / Timeout in seconds"""

    tool_id: Optional[str] = None
    """工具 ID / Tool ID"""

    tool_name: Optional[str] = None
    """工具名称 / Tool name"""

    tool_type: Optional[str] = None
    """工具类型(MCP/FUNCTIONCALL) / Tool type (MCP/FUNCTIONCALL)"""

    version_id: Optional[str] = None
    """版本 ID / Version ID"""

    @classmethod
    def __get_client(cls, config: Optional[Config] = None):
        from .client import ToolClient

        return ToolClient(config)

    @classmethod
    async def get_by_name_async(
        cls, name: str, config: Optional[Config] = None
    ) -> "Tool":
        """异步通过名称获取工具 / Get tool by name asynchronously"""
        cli = cls.__get_client(config)
        return await cli.get_async(name=name)

    @classmethod
    def get_by_name(cls, name: str, config: Optional[Config] = None) -> "Tool":
        """同步通过名称获取工具 / Get tool by name synchronously"""
        cli = cls.__get_client(config)
        return cli.get(name=name)

    async def get_async(self, config: Optional[Config] = None) -> "Tool":
        """异步刷新工具信息 / Refresh tool info asynchronously"""
        effective_name = self.tool_name or self.name
        if effective_name is None:
            raise ValueError("Tool name is required to get the Tool.")

        result = await self.get_by_name_async(
            name=effective_name, config=config
        )
        return self.update_self(result)

    def get(self, config: Optional[Config] = None) -> "Tool":
        """同步刷新工具信息 / Refresh tool info synchronously"""
        effective_name = self.tool_name or self.name
        if effective_name is None:
            raise ValueError("Tool name is required to get the Tool.")

        result = self.get_by_name(name=effective_name, config=config)
        return self.update_self(result)

    def _get_functioncall_server_url(
        self, config: Optional[Config] = None
    ) -> Optional[str]:
        """获取 FunctionCall 工具的 fallback server URL / Get fallback server URL for FunctionCall tools

        当 OpenAPI spec 中没有 servers 字段时，使用 data_endpoint 构造 URL。
        Constructs URL from data_endpoint when servers is not present in OpenAPI spec.
        """
        effective_name = self.tool_name or self.name
        data_endpoint = self.data_endpoint
        if not data_endpoint:
            cfg = Config.with_configs(config)
            data_endpoint = cfg._data_endpoint
        if not data_endpoint or not effective_name:
            return None
        return f"{data_endpoint}/tools/{effective_name}"

    def _get_tool_type(self) -> Optional[ToolType]:
        """获取工具类型 / Get tool type"""
        raw_type = self.tool_type
        if raw_type:
            try:
                return ToolType(raw_type)
            except ValueError:
                return None
        return None

    def _get_mcp_endpoint(
        self, config: Optional[Config] = None
    ) -> Optional[str]:
        """获取 MCP 数据链路 URL / Get MCP data endpoint URL

        根据 session_affinity 决定使用 /mcp 还是 /sse 路径。
        如果 self.data_endpoint 为空，则从 Config 中获取。
        Determines /mcp or /sse path based on session_affinity.
        Falls back to Config if self.data_endpoint is not set.
        """
        effective_name = self.tool_name or self.name
        data_endpoint = self.data_endpoint
        if not data_endpoint:
            cfg = Config.with_configs(config)
            data_endpoint = cfg._data_endpoint
        if not data_endpoint or not effective_name:
            return None

        session_affinity = pydash.get(
            self, "mcp_config.session_affinity", "MCP_SSE"
        )

        if session_affinity == "MCP_STREAMABLE":
            return f"{data_endpoint}/tools/{effective_name}/mcp"
        return f"{data_endpoint}/tools/{effective_name}/sse"

    async def list_tools_async(
        self, config: Optional[Config] = None
    ) -> List[ToolInfo]:
        """异步获取子工具列表 / Get sub-tool list asynchronously

        对于 MCP 类型，通过 MCP 协议获取工具列表。
        对于 FUNCTIONCALL 类型，解析 protocol_spec 获取工具列表。
        For MCP type, gets tool list via MCP protocol.
        For FUNCTIONCALL type, parses protocol_spec to get tool list.

        Returns:
            List[ToolInfo]: 子工具信息列表 / List of sub-tool information
        """
        tool_type = self._get_tool_type()

        if tool_type == ToolType.MCP:
            from .api.mcp import ToolMCPSession

            mcp_endpoint = self._get_mcp_endpoint(config)
            if not mcp_endpoint:
                logger.warning(
                    "MCP endpoint not available for tool %s", self.name
                )
                return []

            session_affinity = pydash.get(
                self, "mcp_config.session_affinity", "MCP_SSE"
            )

            cfg = Config.with_configs(config)
            session = ToolMCPSession(
                endpoint=mcp_endpoint,
                session_affinity=session_affinity,
                headers=cfg.get_headers(),
            )
            return await session.list_tools_async()

        elif tool_type == ToolType.FUNCTIONCALL:
            from .api.openapi import ToolOpenAPIClient

            openapi_client = ToolOpenAPIClient(
                protocol_spec=self.protocol_spec,
                fallback_server_url=self._get_functioncall_server_url(config),
            )
            return await openapi_client.list_tools_async()

        return []

    def list_tools(self, config: Optional[Config] = None) -> List[ToolInfo]:
        """同步获取子工具列表 / Get sub-tool list synchronously

        对于 MCP 类型，通过 MCP 协议获取工具列表。
        对于 FUNCTIONCALL 类型，解析 protocol_spec 获取工具列表。
        For MCP type, gets tool list via MCP protocol.
        For FUNCTIONCALL type, parses protocol_spec to get tool list.

        Returns:
            List[ToolInfo]: 子工具信息列表 / List of sub-tool information
        """
        tool_type = self._get_tool_type()

        if tool_type == ToolType.MCP:
            from .api.mcp import ToolMCPSession

            mcp_endpoint = self._get_mcp_endpoint(config)
            if not mcp_endpoint:
                logger.warning(
                    "MCP endpoint not available for tool %s", self.name
                )
                return []

            session_affinity = pydash.get(
                self, "mcp_config.session_affinity", "MCP_SSE"
            )

            cfg = Config.with_configs(config)
            session = ToolMCPSession(
                endpoint=mcp_endpoint,
                session_affinity=session_affinity,
                headers=cfg.get_headers(),
            )
            return session.list_tools()

        elif tool_type == ToolType.FUNCTIONCALL:
            from .api.openapi import ToolOpenAPIClient

            openapi_client = ToolOpenAPIClient(
                protocol_spec=self.protocol_spec,
                fallback_server_url=self._get_functioncall_server_url(config),
            )
            return openapi_client.list_tools()

        return []

    async def call_tool_async(
        self,
        name: str,
        arguments: Optional[Dict[str, Any]] = None,
        config: Optional[Config] = None,
    ) -> Any:
        """异步调用子工具 / Call sub-tool asynchronously

        Args:
            name: 子工具名称 / Sub-tool name
            arguments: 调用参数 / Call arguments
            config: 配置对象,可选 / Configuration object, optional

        Returns:
            Any: 工具执行结果 / Tool execution result
        """
        tool_type = self._get_tool_type()

        logger.debug("invoke tool %s with arguments %s", name, arguments)

        if tool_type == ToolType.MCP:
            from .api.mcp import ToolMCPSession

            mcp_endpoint = self._get_mcp_endpoint(config)
            if not mcp_endpoint:
                raise ValueError(
                    f"MCP endpoint not available for tool {self.name}"
                )

            session_affinity = pydash.get(
                self, "mcp_config.session_affinity", "MCP_SSE"
            )

            cfg = Config.with_configs(config)
            session = ToolMCPSession(
                endpoint=mcp_endpoint,
                session_affinity=session_affinity,
                headers=cfg.get_headers(),
            )
            result = await session.call_tool_async(name, arguments)
            logger.debug("invoke tool %s got result %s", name, result)
            return result

        elif tool_type == ToolType.FUNCTIONCALL:
            from .api.openapi import ToolOpenAPIClient

            cfg = Config.with_configs(config)
            openapi_client = ToolOpenAPIClient(
                protocol_spec=self.protocol_spec,
                headers=cfg.get_headers(),
                fallback_server_url=self._get_functioncall_server_url(config),
            )
            result = await openapi_client.call_tool_async(name, arguments)
            logger.debug("invoke tool %s got result %s", name, result)
            return result

        raise ValueError(f"Unsupported tool type: {self.tool_type}")

    def call_tool(
        self,
        name: str,
        arguments: Optional[Dict[str, Any]] = None,
        config: Optional[Config] = None,
    ) -> Any:
        """同步调用子工具 / Call sub-tool synchronously

        Args:
            name: 子工具名称 / Sub-tool name
            arguments: 调用参数 / Call arguments
            config: 配置对象,可选 / Configuration object, optional

        Returns:
            Any: 工具执行结果 / Tool execution result
        """
        tool_type = self._get_tool_type()

        logger.debug("invoke tool %s with arguments %s", name, arguments)

        if tool_type == ToolType.MCP:
            from .api.mcp import ToolMCPSession

            mcp_endpoint = self._get_mcp_endpoint(config)
            if not mcp_endpoint:
                raise ValueError(
                    f"MCP endpoint not available for tool {self.name}"
                )

            session_affinity = pydash.get(
                self, "mcp_config.session_affinity", "MCP_SSE"
            )

            cfg = Config.with_configs(config)
            session = ToolMCPSession(
                endpoint=mcp_endpoint,
                session_affinity=session_affinity,
                headers=cfg.get_headers(),
            )
            result = session.call_tool(name, arguments)
            logger.debug("invoke tool %s got result %s", name, result)
            return result

        elif tool_type == ToolType.FUNCTIONCALL:
            from .api.openapi import ToolOpenAPIClient

            cfg = Config.with_configs(config)
            openapi_client = ToolOpenAPIClient(
                protocol_spec=self.protocol_spec,
                headers=cfg.get_headers(),
                fallback_server_url=self._get_functioncall_server_url(config),
            )
            result = openapi_client.call_tool(name, arguments)
            logger.debug("invoke tool %s got result %s", name, result)
            return result

        raise ValueError(f"Unsupported tool type: {self.tool_type}")
